services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nowo\AuditKitBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Model/'
            - '../../Attribute/'
            - '../../NowoAuditKitBundle.php'

    Nowo\AuditKitBundle\Profile\ProfileRegistry:
        arguments:
            $profiles: '%nowo_audit_kit.profiles%'
            $defaultProfileName: '%nowo_audit_kit.default_profile%'

    Nowo\AuditKitBundle\Doctrine\AuditablePropertyResolver: ~

    Nowo\AuditKitBundle\Doctrine\AuditableEntityListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, entity: null, lazy: true }
            - { name: doctrine.orm.entity_listener, event: preUpdate, entity: null, lazy: true }
